import type { Assessment, CompanySettings } from '$lib/types/assessment';
import { formatDateNumeric } from '$lib/utils/formatters';

interface PhotoSection {
	title: string;
	photos: Array<{
		url: string;
		caption?: string;
	}>;
}

interface PhotosData {
	assessment: Assessment;
	companySettings: CompanySettings | null;
	sections: PhotoSection[];
}

export function generatePhotosHTML(data: PhotosData): string {
	const { assessment, companySettings, sections } = data;

	const renderPhotoSection = (section: PhotoSection) => {
		if (section.photos.length === 0) return '';

		return `
		<div class="section">
			<div class="section-title">${section.title}</div>
			<div class="photos-grid">
				${section.photos
					.map(
						(photo) => `
					<div class="photo-item">
						<img src="${photo.url}" alt="${photo.caption || section.title}" />
						${photo.caption ? `<div class="photo-caption">${photo.caption}</div>` : ''}
					</div>
				`
					)
					.join('')}
			</div>
		</div>
		`;
	};

	return `
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Assessment Photographs - ${assessment.assessment_number}</title>
	<style>
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
		}

		body {
			font-family: Arial, sans-serif;
			font-size: 10pt;
			line-height: 1.4;
			color: #000;
		}

		.header {
			background-color: #1e40af;
			color: white;
			padding: 20px;
			text-align: center;
			margin-bottom: 20px;
		}

		.header h1 {
			font-size: 24pt;
			margin-bottom: 10px;
		}

		.company-info {
			font-size: 9pt;
			margin-top: 10px;
		}

		.photos-title {
			background-color: #3b82f6;
			color: white;
			padding: 10px;
			text-align: center;
			font-size: 16pt;
			font-weight: bold;
			margin-bottom: 20px;
		}

		.info-box {
			background-color: #f3f4f6;
			padding: 15px;
			margin-bottom: 20px;
			border-left: 4px solid #3b82f6;
		}

		.info-row {
			display: inline-block;
			margin-right: 30px;
			margin-bottom: 5px;
		}

		.info-label {
			font-weight: bold;
			color: #374151;
		}

		.info-value {
			color: #000;
			margin-left: 5px;
		}

		.section {
			margin-bottom: 30px;
			page-break-inside: avoid;
		}

		.section-title {
			background-color: #dbeafe;
			padding: 10px;
			font-weight: bold;
			font-size: 12pt;
			border-left: 4px solid #3b82f6;
			margin-bottom: 15px;
		}

		.photos-grid {
			display: grid;
			grid-template-columns: repeat(2, 1fr);
			gap: 20px;
			margin-bottom: 20px;
		}

		.photo-item {
			border: 1px solid #d1d5db;
			padding: 10px;
			background-color: #fff;
			text-align: center;
		}

		.photo-item img {
			max-width: 100%;
			height: auto;
			max-height: 400px;
			object-fit: contain;
			display: block;
			margin: 0 auto;
		}

		.photo-caption {
			margin-top: 10px;
			font-size: 9pt;
			color: #6b7280;
			font-style: italic;
		}

		.footer {
			margin-top: 30px;
			padding-top: 20px;
			border-top: 2px solid #3b82f6;
			text-align: center;
			font-size: 9pt;
			color: #6b7280;
		}

		.page-break {
			page-break-after: always;
		}

		@media print {
			.section {
				page-break-inside: avoid;
			}
		}
	</style>
</head>
<body>
	<!-- Header -->
	<div class="header">
		<h1>${companySettings?.company_name || 'Claimtech'}</h1>
		<div class="company-info">
			${companySettings?.po_box || 'P.O. Box 12345'}<br>
			${companySettings?.city || 'Johannesburg'}, ${companySettings?.province || 'Gauteng'}<br>
			${companySettings?.postal_code || '2000'}<br>
			Tel: ${companySettings?.phone || '+27 (0) 11 123 4567'}
		</div>
	</div>

	<!-- Photos Title -->
	<div class="photos-title">
		ASSESSMENT PHOTOGRAPHS
	</div>

	<!-- Assessment Information -->
	<div class="info-box">
		<div class="info-row">
			<span class="info-label">Assessment No.:</span>
			<span class="info-value">${assessment.assessment_number}</span>
		</div>
		<div class="info-row">
			<span class="info-label">Report No.:</span>
			<span class="info-value">${assessment.report_number || 'N/A'}</span>
		</div>
		<div class="info-row">
			<span class="info-label">Date:</span>
			<span class="info-value">${formatDateNumeric(assessment.created_at)}</span>
		</div>
	</div>

	<!-- Photo Sections -->
	${sections.map((section) => renderPhotoSection(section)).join('')}

	${sections.every((s) => s.photos.length === 0) ? `
	<div class="section">
		<p style="text-align: center; color: #6b7280; padding: 40px;">No photographs available for this assessment.</p>
	</div>
	` : ''}

	<!-- Footer -->
	<div class="footer">
		<p>This document was generated by ${companySettings?.company_name || 'Claimtech'}</p>
		<p>${companySettings?.email || 'info@claimtech.co.za'} | ${companySettings?.website || 'www.claimtech.co.za'}</p>
		<p>Document generated on ${formatDateNumeric(new Date().toISOString())}</p>
	</div>
</body>
</html>
	`.trim();
}

